apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "redis.fullname" . }}
  labels:
    app: redis
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "redis.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "redis.fullname" . }}
    spec:
      containers:
      - name: {{ template "redis.fullname" . }}
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        ports:
        - name: http
          containerPort: {{ .Values.redis.service.servicePort }}