apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "sisfogo2.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "sisfogo2.name" . }}
    spec:
      containers:
      - name: redis-sisfogo2
        image: redis:4.0.9-alpine
        ports:
        - name: redis
          containerPort: 6379