apiVersion: v1
kind: Service
metadata:
  name: redis-sisfogo2
  labels:
    app: redis
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: {{ template "sisfogo2.name" . }}
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
