secret:
  name: registry-secret
  auth:
    registryadminpassword: Reg2018BASIS # base64 encoded = UmVnMjAxOEJBU0lT"

jhipster:
  name: jhipster-registry
  port: 8761
  replicaCount: 2
  image: jhipster/jhipster-registry:v4.0.0

service:
  name: jhipster-registry
  port: 8761

configmap:
  name: jhipster-registry
  application:
    spring:
      profilesactive: prod,swagger,k8s
    eureka:
      client:
        initialinstanceinforeplicationintervalseconds: 15
        instanceinforeplicationintervalseconds: 15
        registryfetchintervalseconds: 15
        fetchregistry: true
        registerwitheureka: true
        eurekaserviceurlpollintervalseconds: 15
      server:
        peereurekanodesupdateintervalms: 15000
        renewalthresholdupdateintervalms: 15000
        peernodeconnecttimeoutms: 2000
        enableselfpreservation: false
        registrysyncretries: 3
        composite0type: native
        composite0searchlocations: file:./central-config
      instance:
        leaserenewalintervalinseconds: 15
        leaseexpirationdurationinseconds: 30
        registrydefaultopenfortrafficcount: 0    
    jhipster:
      securityauthenticationjwtsecret: change_it #IUydTY4W2Sis95MDwe10BK4GvrRTVHpumdQPZYt229zn1PEh24HL7xWq6sk6tg7t6NZz35oEH0t8h0UhA3JDNEn81o896X7O
  jhipster:
    eureka:
      client:
        serviceurl:
          defaultZone: http://admin:${spring.security.user.password}@jhipster-registry-0.jhipster-registry.discovery.svc.cluster.local:8761/eureka/,http://admin:${spring.security.user.password}@jhipster-registry-1.jhipster-registry.discovery.svc.cluster.local:8761/eureka/     
