name: redis
version: 0.0.1
appVersion: 0.0.1
description: redis.
keywords:
- redis

home: 
icon: https://cdn-images-1.medium.com/max/1600/1*ngGAAMf8Sw4jCJ_nP2Qt5A.png
maintainers:
- name: Basis
  email: basis@basis.com.br
